ALTER TABLE `User`
  MODIFY COLUMN `globalRole` ENUM('SUPER_ADMIN', 'ADMIN', 'USER', 'CLIENT', 'WORKER', 'RESPONSIBLE') NOT NULL DEFAULT 'USER';

ALTER TABLE `Bar` ADD COLUMN `clientUserId` VARCHAR(191) NULL;
CREATE INDEX `Bar_clientUserId_idx` ON `Bar`(`clientUserId`);
ALTER TABLE `Bar` ADD CONSTRAINT `Bar_clientUserId_fkey` FOREIGN KEY (`clientUserId`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
