ALTER TABLE `StockMovement`
  MODIFY COLUMN `type` ENUM('INITIAL_LOAD', 'TRANSFER', 'DELIVERY', 'RETURN', 'CLEANING_SEND', 'CLEANING_RETURN', 'ADJUSTMENT', 'LOSS', 'BREAKAGE', 'SALE') NOT NULL;

ALTER TABLE `CashMovement`
  MODIFY COLUMN `type` ENUM('INITIAL_CASH', 'CASH_IN', 'CASH_OUT', 'COLLECTION', 'WITHDRAWAL', 'EXPENSE', 'ADJUSTMENT', 'FINAL_SETTLEMENT', 'REFUND', 'SALE') NOT NULL;
